site_name: OpenRA
site_description: Trait description and Lua API documentation
docs_dir: api
extra_css:
    - css/extra.css
pages:
    - 'index.md'
    - 'lua.md'
    - 'sprite-sequences.md'
    - 'traits.md'
    - 'weapons.md'
    - 'Version':
        - 'Release': 'https://docs.openra.net/en/release/'
        - 'Playtest': 'https://docs.openra.net/en/playtest/'
