site_name: OpenRA
site_description: Trait description and Lua API documentation
site_url: https://openra.net
edit_uri: ""
docs_dir: api
extra_css:
  - css/extra.css
theme:
  name: material
  features:
    - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenRA/OpenRA
